
# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
webserver_image:
  repository: paulkellerman/phonebookapp-webserver:latest
  tag: webserver
  replicaCount: 3


resultserver_image:
  repository: paulkellerman/phonebookapp-resultserver:latest
  tag: resultserver
  replicaCount: 2

mysql_image:
  repository: mysql:5.7
  tag: mysql
  containerPort: 3306
  replicaCount: 1

webserver_service:
  type: NodePort
  port: 80
  targetport: 80
  nodePort: 30005
  tag: webserver

resultserver_service:
  type: NodePort
  port: 80
  targetport: 80
  nodePort: 30006
  tag: resultserver

db_service:
  type: ClusterIP
  port: 3306
  targetport: 3306
  tag: mysql

volumes:
  - name: mysql-storage2
    persistentVolumeClaim:
      claimName: mysql-pv-claim

volumeMounts: 
  - name: mysql-storage2
    mountPath: "/var/lib/mysql"

storage:
  size: 5Gi
  path: "/home/data2"
  storageClassName: manual
  accessMode: ReadWriteOnce

ingress:
  name: nginx
  paths:
    - path: /
      pathType: Prefix
      service:
        name: webserver-svc
        port: 80
    - path: /result
      pathType: Prefix
      service:
        name: resultserver-svc
        port: 80



