apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    app: {{ .Values.db-service.tag}}
spec:
  storageClassName: {{ .Values.storage.storageClassName }}
  capacity:
    storage: {{ .Values.storage.size }}
  accessModes:
    - {{ .Values.storage.accessMode}}
  hostPath:
    path: {{ .Values.storage.path}}