apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels:
    app: {{ .Values.db_service.tag | default "mysql" }}
spec:
  selector:
      app: {{ .Values.db_service.tag | default "mysql" }}
  type: {{ .Values.db_service.type }}
  ports:
    - name: db
      port: {{ .Values.db_service.port }}
      targetPort: {{ .Values.db_service.targetport }}
