apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels:
    app: {{ .Values.db-service.tag }}
spec:
  selector:
      app: {{ .Values.db-service.tag }}
  type: {{ .Values.db-service.type }}
  ports:
    - name: db
      port: {{ .Values.db-service.port }}
      targetPort: {{ .Values.db-service.targetport }}
