apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: phonebook-ingress-5
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /web
            pathType: Prefix
            backend:
              service:
                name: webserver-svc
                port: 
                  number: 80
          - path: /results
            pathType: Prefix
            backend:
              service: 
                name: resultserver-svc
                port: 
                  number: 80
