apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: phonebook-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: {{ .Values.ingress.name }}
  rules:
    - http:
        paths:
          {{- range .Values.ingress.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ .service.name }}
                port:
                  number: {{ .service.port }}
          {{- end }}

          # - path: /
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: webserver-svc
          #       port: 
          #         number: {{ .Values.ingress.port }}

          # - path: /result
          #   pathType: Prefix
          #   backend:
          #     service: 
          #       name: resultserver-svc
          #       port: 
          #         number: {{ .Values.ingress.port }}
