apiVersion: v1
kind: Service
metadata:
  name: webserver-svc
  labels:
    app: {{ .Values.webserver-service.tag }}
spec:
  selector:
    app: {{ .Values.webserver-service.tag }}
  type: {{ .Values.webserver-service.type }}
  ports:
   - name: http
     port: {{ .Values.webserver-service.port }}
     targetPort: {{ .Values.webserver-service.targetport }}
     nodePort: {{ .Values.webserver-service.nodePort }}
     protocol: TCP