apiVersion: v1
kind: Service
metadata:
  name: webserver-svc
  labels:
    app: {{ .Values.webserver_service.tag }}
spec:
  selector:
    app: {{ .Values.webserver_service.tag }}
  type: {{ .Values.webserver_service.type }}
  ports:
    - name: http
      port: {{ .Values.webserver_service.port }}
      targetPort: {{ .Values.webserver_service.targetport }}
      nodePort: {{ .Values.webserver_service.nodePort }}
      protocol: TCP