apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-deployment
  labels:
    app: {{ .Values.webserver_image.tag }}
spec:
  replicas: {{ .Values.webserver_image.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.webserver_image.tag }}
  template:
    metadata:
      labels:
        app: {{ .Values.webserver_image.tag }}
    spec:
      containers:
      - name: {{ .Values.webserver_image.tag }}
        image: {{ .Values.webserver_image.repository }}
        ports:
          - containerPort: 80
        envFrom:
        - configMapRef:
            name: phonebook-configmap
        - secretRef:
            name: phonebook-secret
